first commit
MegaVerkruzo/tinkoff-fintech-refactoring-task pull request #1
Opened 2022-02-26 10:28 UTC by MegaVerkruzo

2022-03-03 09:21 UTC, mplain requested changes

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/MainKt.kt
> +    val orderQueue = OrderQueue()
почему ты отказался от PizzaStore в пользу некой очереди?

в пиццерию попала бомба и теперь работники готовят пиццу на улице?

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +data class FoodOrder(
почему публичный дата-класс не в своем файле, а в файле сервиса?

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +        return null
на фукнциональщине этой выглядит так:
```
fun existsProcessedFood(name: String): ProcessedFood? =
        cuisines.find { it.existsProcessedFood(name) }
```

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +    fun existsProcessedFood(name: String): ProcessedFood? {
функция с названием existsProcessedFood должна возвращать Boolean

возвращать ProcessedFood? должна функция с названием что-то типа processFood или tryProcessFood

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +    fun existsProcessedFood(name: String): ProcessedFood? {
как ты для себя переводишь ProcessedFood? приготовленная еда? может лучше cooked?

processed - это по-моему больше про завод по очистке рыбы, чем про то что подается на стол...

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +        val ProcessedFoodType = existsProcessedFood(name) ?: error("Неизвестный вид еды!")
имя переменной не должно начинаться с заглавной буквы, это противоречит конвенции именования в джаве и котлине (и Идея это подсвечивает)

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/cuisine/CuisineFood.kt
> +    fun existsProcessedFood(name: String): ProcessedFood? {
что это за враппер, в чем идея?

нельзя ли то же самое сделать через enum?

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/employee/PizzaMaker.kt
> +    override fun cleanFloor(): Boolean {
насколько я понял, идея автора домашки была в том, что у классов не должно быть методов, которые они не умеют выполнять

скорее у класса Employee должен быть абстрактный метод doWork, и каждый подкласс умеет выполнять свою работу

чтобы каждый подкласс получал в doWork аргумент только своего типа, можно сделать Employee типизированным (дженерик)

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Coffee.kt
> +    override val ingredients: List<Pair<Ingredient, Int>> = listOf()
почему не мапа?

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Food.kt
> +interface ProcessedFood : SimpleFood {
CookedFood ?

2022-03-03 09:21 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Pizza.kt
> +            val count: Int = ingredient.second
destructuring declaration
```
ingredients.forEach { (ingredient, count) ->
```

2022-03-03 10:14 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/MainKt.kt
> +    val orderQueue = OrderQueue()
OrderQueue можно переименовать и в PizzaStore. По сути будет одно и то же выполняться. Просто я назвал по другому, потому что хотел выделить две разных типа блюд, которые могут готовить CuisineCoffee и CuisinePizza - это соответсвующие классы. 

В общем, да. Думаю стоит переименовать этот класс OrderQueue обратно в PizzaStore, так будет ближе к исходному коду

2022-03-03 10:14 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +data class FoodOrder(
Хмм, интересный вопрос. Сейчас поправлю

2022-03-03 10:26 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/cuisine/CuisineFood.kt
> +    fun existsProcessedFood(name: String): ProcessedFood? {
Я столкнулся с проблемой того, как мне писать existsProccessedFood, если у меня нет массива с перечислением типов кофе или типов пиццы. Я придумал такой метод
Но с enum вроде будет годнее, погуглю, попробую встроить enum, чтобы было получше

2022-03-03 10:27 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +        val ProcessedFoodType = existsProcessedFood(name) ?: error("Неизвестный вид еды!")
В шоке, как я это не заметил

2022-03-03 10:28 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/employee/PizzaMaker.kt
> +    override fun cleanFloor(): Boolean {
Отличная замечание!!
Я исправлю

2022-03-03 10:29 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Coffee.kt
> +    override val ingredients: List<Pair<Ingredient, Int>> = listOf()
Со списочком быстрее работать, и он меньше весит. Чем мапа, которая строиться на дереве и обращение к элементу происходит за O(log N), понимаю, что это уже придирки. Но здесь я решил не поскупиться на производительность

2022-03-03 10:30 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Food.kt
> +interface ProcessedFood : SimpleFood {
Да, я поменяю

2022-03-03 10:30 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Pizza.kt
> +            val count: Int = ingredient.second
Так и правда лучше

2022-03-03 14:39 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +        return null
Поменял, где мог

2022-03-03 14:39 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +    fun existsProcessedFood(name: String): ProcessedFood? {
Исправил

2022-03-03 14:42 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/OrderQueue.kt
> +        val ProcessedFoodType = existsProcessedFood(name) ?: error("Неизвестный вид еды!")
Поправил

2022-03-03 14:59 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Pizza.kt
> +            val count: Int = ingredient.second
Исправил

2022-03-03 15:00 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Food.kt
> +interface ProcessedFood : SimpleFood {
Исправил

2022-03-04 10:01 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/cuisine/CuisineFood.kt
> +    fun existsProcessedFood(name: String): ProcessedFood? {
Поменял на enum

2022-03-04 18:35 UTC, mplain requested changes

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    private var orderNumber: Int = 0,
вряд ли это должно быть в конструкторе

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    private val orders: MutableMap<FoodOrder, Boolean> = mutableMapOf()
а это вообще бэкдор, можно создать пиццерию, передав ей в конструктор пустую мутабельную мапу, с которой она будет работать, но оставить ссылку на мапу, и в любой момент изменить мапу снаружи

не надо все поля пихать в конструктор

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    fun existsCoffee(name: String): Boolean =
если функцию не вызывают снаружи, она должна быть приватной

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    fun coffee(name: String): Coffee {
непонятно по сигнатуре, что делает функция. она делает кофе. она создает кофе? или обрабатывает заказ на кофе? или что?

имя функции должно начинаться с глагола

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            return Coffee.values().find { coffee -> coffee.title == name }!!
ты делаешь одно и то же в existsCoffee и здесь. двойная работа

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            return Coffee.values().find { coffee -> coffee.title == name }!!
`.find { ... }!!` -> `.first { ... }`

вообще использование !! - это признак лени

!! кидает NPE, а это максимально неудобно при дебаге. всегда следует использовать какой-то другой вариант, если есть. а здесь он есть

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            return Pizza.values().find { pizza -> pizza.title == name }!!
аналогично

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            pizza(name)
двойная работа

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            error("Неизвестный вид еды!")
```
when {
     existsPizza -> pizza
     existsCoffee -> coffee
     else -> error
}
```
или
```
getPizza(name) ?: getCoffee(name) ?: error
```
но это уже нерасширяемо

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        orders[foodOrder] = true
это что значит, в чем идея?

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    fun executeOrder(foodOrder: FoodOrder?) {
зачем функция принимает нуллабельный аргумент? не надо так

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        if (foodOrder != null && orders[foodOrder] != null) {
зачем вообще разделение на order и executeOrder?

заказ нужен для чего-то между этими двумя вызовами?

я бы понял если бы очереди были

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +                Barista().doWork(foodOrder.number, foodOrder.cookedFood)
почему создаем нового баристу под каждый заказ?

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            }
`else if` -> `when`

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            error("Сотрудника, который может приготовить такую еду - нет!")
преждевременный ретурн и ошибка в конце функции - нежелательно так писать код

здесь как минимум можно else сделать

2022-03-04 18:35 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Coffee.kt
> +    override val ingredients: Map<Ingredient, Int> = mapOf()
если в кофе нет ингридиентов, может это поле и не должно присутствовать в CookedFood? только в Pizza?

2022-03-06 18:49 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    private var orderNumber: Int = 0,
Решил эту проблему

2022-03-06 18:49 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    private val orders: MutableMap<FoodOrder, Boolean> = mutableMapOf()
Да, ты прав

2022-03-06 23:55 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    fun coffee(name: String): Coffee {
Удалил

2022-03-06 23:55 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            return Pizza.values().find { pizza -> pizza.title == name }!!
Удалил эти функции

2022-03-06 23:59 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            error("Неизвестный вид еды!")
Я поправил на другой вариант, но к сожалению я не понимаю, как это расширять. Потому что в set я не могу запихнуть enum классы, из-за этого. Я ограничен пока только ?:

2022-03-07 00:03 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        orders[foodOrder] = true
идея в том после функции order возвращался как бы чек с заказом(order: FoodOrder), а далее при вызове функции executeOrder(order: FoodOrder) - мы даём этот чек менеджеру, который скажет готовить этот заказ

2022-03-07 00:04 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    fun executeOrder(foodOrder: FoodOrder?) {
Теперь этой функции нет в моей новой реализации

2022-03-07 00:07 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        if (foodOrder != null && orders[foodOrder] != null) {
У нас в изначальной версии было две функции order и executeOrder. Я понял их, как описывал в пред. сообщении # [#](https://github.com/MegaVerkruzo/tinkoff-fintech-refactoring-task/pull/1#discussion_r820308973)

2022-03-07 00:08 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +                Barista().doWork(foodOrder.number, foodOrder.cookedFood)
Теперь не создаю

2022-03-07 00:08 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            error("Сотрудника, который может приготовить такую еду - нет!")
Исправил

2022-03-07 07:05 UTC, mplain requested changes

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/FoodOrder.kt
> +data class FoodOrder<out T : SimpleFood>(
почему out? какое обоснование?

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/FoodOrder.kt
> +    val orderId: Int,
можно просто id

обычно собственный адишник сущности обозначается просто id, а ссылки на другие объекты уже могут быть smtnId

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        if (food != null) {
если у тебя структура `if (...) ... else throw`, то можно ее переделать в такую:
```
if (!...) throw
...
```
то есть ветвление переделываешь в валидацию

как преимущество убираешь отступ 

не принципиальный момент, на вкус и цвет

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        error("Неизвестный тип еды!")
лично мне очень не нравится стурктура метода в преждевременным return, и ошибкой в конце метода

хотя бы вместо
```
if (...) {
   ...
}
throw ...
```
сделай
```
if (...) {
   ...
} else {
   throw ...
}
```
а лучше валидация
```
if (!...) throw ...
...
```
в котлине стараемся писать в функциональном стиле, который предусматривает один выход (return) из функции, в самом ее конце

преждевременные throw возможны, но преждевременные return нежелательны

другие могут иметь другую точку зрения, но я придерживаюсь этой и буду просить делать так

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        val food: SimpleFood? = Coffee.values().find { it.title == name } ?: Pizza.values().find { it.title == name }
можно сделать так:
```
val food = Coffee.values().find { it.title == name }
                ?: Pizza.values().find { it.title == name }
                ?: error("Нет такого блюда в меню")
```

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            employees.find { it.canCook(order) }?.cookFood(order)
а если подходящего работника не нашли?

типа всё ок, хотя работу никакую не выполнили

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/FoodOrder.kt
> +data class FoodOrder<out T : SimpleFood>(
я не увидел в коде нигде использования типизированного параметра (проглядел?), везде только `FoodOrder<SimpleFood>`

здесь действительно нужен дженерик? или можно просто сделать `val food: SimpleFood`

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/employee/Barista.kt
> +        if (order.food is Coffee) {
лучше валидация

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/employee/PizzaMaker.kt
> +        if (order.food is Pizza) {
лучше валидация

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Coffee.kt
> +    val cookingTime: Int,
brewTime ?

2022-03-07 07:05 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            if (employees.find { it.canCook(order) } != null) {
у меня сомнения по поводу логики процесса

сначала покупатель делает заказ - проверяется есть ли блюдо в меню + есть ли подходящий работник (1) - заказ добавляется в базу заказов

потом поступает команда на выполнение заказа (от кого?): находим подходящего работника (2), поручаем ему приготовить еду - он первым делом проверяет может ли он это сделать (3)

итого проверка `if food is T` делается три раза. нельзя ли что-то с этим сделать, как-то упростить? мне с ходу ничего конкретного в голову не приходит. посмотри, если ничего не придумаешь элегантного, то оставим так, уже нет времени переделывать основательно

и непонятно зачем разнесены методы получения заказа и его выполнения

можно предположить, что предполагается очередь на кассе + очередь в окошке выдачи, просто не успели реализовать. ну ок, пусть так

2022-03-07 07:09 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Coffee.kt
> +enum class Coffee(
ты перенес кофе в отдельный пакет food

вообще вполне возможно что это осмысленно и хорошо

но в этой домашке получается, что ты удалил один файл Coffee и добавил другой файл Coffee

мне так сложнее ревьюить, не могу на одном экране сопоставлять изменения, приходится прыгать по коду

верни пожалуйста структуру проекта ближе к оригиналу, чтобы мне было полегче

2022-03-07 07:43 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            return Coffee.values().find { coffee -> coffee.title == name }!!
убрал

2022-03-07 08:11 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/employee/Employee.kt
> +interface Employee<in T : SimpleFood> {
зачем in ?

2022-03-07 08:27 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        if (food != null) {
Попробовал, но выглядит вроде менее читаемо, в общем и правда на вкус и цвет:)

2022-03-07 08:32 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        error("Неизвестный тип еды!")
Понял, о чём ты говоришь. Поправил

2022-03-07 09:17 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            employees.find { it.canCook(order) }?.cookFood(order)
Такой ситуации не существует, потому что мы её обрабатываем в order

2022-03-07 09:44 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/food/Coffee.kt
> +enum class Coffee(
Вернул

2022-03-07 09:52 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +            if (employees.find { it.canCook(order) } != null) {
Я делал, оперевшись на начальный код. И мы там, как раз брали pizzaOrder и клали его, как аргумент в ф-ию executeOrder

2022-03-07 10:07 UTC, mplain requested changes

2022-03-07 10:07 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/Barista.kt
> +        if (order.food !is Coffee) error("[Бариста] не может выполнить этот заказ")
переиспользуй код
```
if (!canCook(order)) error(...)
```

2022-03-07 10:07 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaMaker.kt
> +        if (order.food !is Pizza) error("[Пицца мейкер] не может выполнить этот заказ")
переиспользуй код

2022-03-07 10:07 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    private val employees: Set<Employee> = setOf()
сомнительно, что нужен такой дефолт, ведь с ним пиццерия не сможет работать по факту

2022-03-07 10:07 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +        if (employees.find { it.canCook(order) } == null)
```
if (employees.none { it.canCook(order) })
```

2022-03-07 10:07 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    private val orders: MutableMap<FoodOrder, Boolean> = mutableMapOf()
мне чот не нравится така реализация, неочевидно что значит true, false и отсутствие элемента

может переделаем так?
```
private val orders = MutableSet<Int>
```
order() добавляет orider.id в сет, execute order убирает

2022-03-07 10:14 UTC, mplain requested changes

2022-03-07 10:14 UTC, mplain commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/Barista.kt
> +        if (order.food !is Coffee) error("[Бариста] не может выполнить этот заказ")
вообще можно еще сделать так:
```
interface Employee {
    val title: String
    fun canCook(order: FoodOrder): Boolean
    protected fun validate(order: FoodOrder) {
        if (!canCook(order))  error("[$title] не может выполнить этот заказ")
    }

```

2022-03-07 17:27 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/Barista.kt
> +        if (order.food !is Coffee) error("[Бариста] не может выполнить этот заказ")
Если я переиспользую код, то у меня код не компилируется

2022-03-07 19:58 UTC, MegaVerkruzo commented on src/main/kotlin/ru/tinkoff/fintech/refactoring/PizzaStore.kt
> +    private val orders: MutableMap<FoodOrder, Boolean> = mutableMapOf()
Я изменил на MutableSet<FoodOrder>, мне нужно большее данных, чем только order.id

2022-03-07 20:31 UTC, mplain approved these changes

2022-03-08 09:55 UTC, merged